name: zenstate
description: A complete, scalable, developer-friendly, and future-proof state management package for Flutter. Features atomic state management, derived state, command pattern, store architecture, and more.
version: 0.0.1
homepage: https://github.com/Ddtarsariya/zenstate
repository: https://github.com/Ddtarsariya/zenstate
issue_tracker: https://github.com/Ddtarsariya/zenstate/issues
topics:
  - flutter
  - state-management
  - dart
  - reactive-programming
  - flutter-package

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.3
  connectivity_plus: ^6.1.4
  battery_plus: ^6.2.1
  uuid: ^4.5.1
  pub_semver: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

